name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js for Yarn (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: client/yarn.lock

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/yarn
          key: ${{ runner.os }}-deps-${{ hashFiles('server/pnpm-lock.yaml', 'client/yarn.lock') }}

      # ------------------------------
      # 🧠 BACKEND JOBS (only if backend changed)
      # ------------------------------
      - name: Detect backend changes
        id: backend_changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            server/**
            shared/**
            package.json
            pnpm-lock.yaml

      - name: Install backend dependencies
        if: steps.backend_changes.outputs.any_changed == 'true'
        run: pnpm install
        working-directory: ./server

      - name: Run backend tests
        if: steps.backend_changes.outputs.any_changed == 'true'
        run: pnpm test
        working-directory: ./server

      # ------------------------------
      # 🎨 FRONTEND JOBS (only if frontend changed)
      # ------------------------------
      - name: Detect frontend changes
        id: frontend_changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            client/**
            shared/**
            package.json
            yarn.lock

      - name: Install frontend dependencies
        if: steps.frontend_changes.outputs.any_changed == 'true'
        run: yarn install --frozen-lockfile
        working-directory: ./client

      - name: Run frontend tests
        if: steps.frontend_changes.outputs.any_changed == 'true'
        run: yarn test --watchAll=false --passWithNoTests
        working-directory: ./client

      - name: Build frontend (Next.js)
        if: steps.frontend_changes.outputs.any_changed == 'true'
        run: yarn build
        working-directory: ./client
