name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/yarn
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml', '**/yarn.lock') }}

      - name: Install backend dependencies
        run: pnpm install
        working-directory: ./server

      - name: Run backend tests
        run: pnpm test
        working-directory: ./server

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./client

      - name: Run frontend tests
        run: yarn test --watchAll=false --passWithNoTests
        working-directory: ./client

      - name: Build frontend (Next.js)
        run: yarn build
        working-directory: ./client
