name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      # --- Checkout repository ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Setup PNPM (backend) ---
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # --- Setup Node.js + cache Yarn ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # --- Cache both pnpm + Yarn deps ---
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/yarn
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pnpm-lock.yaml', '**/yarn.lock') }}

      # --- Install backend dependencies ---
      - name: Install backend dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./server

      # --- Run backend tests ---
      - name: Run backend tests
        run: pnpm test
        working-directory: ./server

      # --- Install frontend dependencies ---
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./client

      # --- Run frontend tests ---
      - name: Run frontend tests
        run: yarn test --watchAll=false --passWithNoTests
        working-directory: ./client

      # --- Build frontend (Next.js) ---
      - name: Build frontend (Next.js)
        run: yarn build
        working-directory: ./client
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NODE_ENV: production
